version: "3.9"

services:
  backend:
    build:
      context: ./
      dockerfile: backend/Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - ENV=development

  frontend:
    build:
      context: ./
      dockerfile: frontend/Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
